name: Build raylib Libraries (Android)

on: [workflow_dispatch]

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v4.1.7
      with:
        repository: 'raysan5/raylib'
        path: 'raylib'
        ref: '5.5'
        submodules: true

    - name: Install dependencies on Ubuntu
      run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake ninja-build wget
          
    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: 17
  
    - name: Install Android SDK Command-Line Tools
      run: |
          wget https://dl.google.com/android/repository/commandlinetools-linux-10406996_latest.zip -O android-sdk-tools.zip
          unzip android-sdk-tools.zip -d tools
          mkdir $HOME/android-sdk/
          mkdir $HOME/android-sdk/cmdline-tools/
          mkdir $HOME/android-sdk/cmdline-tools/latest/
          mv ./tools/cmdline-tools/* $HOME/android-sdk/cmdline-tools/latest/
          chmod +x $HOME/android-sdk/cmdline-tools/latest/bin/*
          echo "ANDROID_HOME=$HOME/android-sdk" >> $GITHUB_ENV
          echo "ANDROID_SDK_ROOT=$HOME/android-sdk" >> $GITHUB_ENV
          
    - name: Accept Android SDK Licenses
      run: |
          yes | $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager --licenses
    - name: Install Specific Android NDK Version 26.3.11579264
      run: |
          yes | $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager --install "ndk;26.3.11579264"      
          yes | $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager --install "build-tools;29.0.3"
          yes | $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager --install "platform-tools"
          yes | $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager --install "platforms;android-28"
          yes | $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager --install "extras;google"
          echo "ANDROID_NDK_HOME=$ANDROID_HOME/ndk/26.3.11579264" >> $GITHUB_ENV
          echo "PATH=$PATH:$ANDROID_HOME/ndk/26.3.11579264" >> $GITHUB_ENV
  
    - name: Build for arm64-v8a
      run: |
            cmake -G "Ninja" -DCMAKE_BUILD_TYPE=Release \
                  -DCMAKE_SYSTEM_NAME=Android \
                  -DCMAKE_ANDROID_NDK=$ANDROID_NDK_HOME \
                  -DCMAKE_ANDROID_ARCH_ABI=arm64-v8a \
                  -DCMAKE_ANDROID_NDK_TOOLCHAIN_VERSION=clang \
                  -S raylib \
                  -B raylib/build/arm64-v8a -DBUILD_SHARED_LIBS=ON -DBUILD_EXAMPLES=OFF -DPLATFORM=Android
            cmake --build raylib/build/arm64-v8a  --config Release
  
    - name: Build for x86_64
      run: |
            cmake -G "Ninja" -DCMAKE_BUILD_TYPE=Release \
                  -DCMAKE_SYSTEM_NAME=Android \
                  -DCMAKE_ANDROID_NDK=$ANDROID_NDK_HOME \
                  -DCMAKE_ANDROID_ARCH_ABI=x86_64 \
                  -DCMAKE_ANDROID_NDK_TOOLCHAIN_VERSION=clang \
                  -S raylib \
                  -B raylib/build/x86_64 -DBUILD_SHARED_LIBS=ON -DBUILD_EXAMPLES=OFF -DPLATFORM=Android
            cmake --build raylib/build/x86_64 --config Release
  

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4.3.4
      with:
        name: raylib-android-latest-all-artifacts 
        path: |
          raylib/build/arm64-v8a/raylib/*.so
          raylib/build/x86_64/raylib/*.so
        if-no-files-found: ignore # 'warn' or 'ignore' or 'error'
